### ISSUE TITLE
Milestone v0.1.0 discussion

### ISSUE THREAD

**Issue by fnery** [UKRIN-MAPS/ukat#14]
Let's use this issue to discuss topics related to [milestone v0.1.0](https://github.com/UKRIN-MAPS/UKRIN-MAPS/milestone/1).

### Milestone goals
- Ensure everyone is familiar with GitHub and able to contribute to it (e.g. raise issues, submit pull requests, etc...)
- Agree on conventions for code, repository structure and test data
- Implement first version of methods for B0 and T2* mapping

### To do

- [x] Provide github walkthrough to UKRIN-MAPS members @fnery 
- [x] Simplify installation #22 @JSousa-UoL @fnery 
- [x] Decide on first version of architecture for data fetchers #16 @fnery 
- [x] Upload Philips b0 mapping test data #26 @charlotteebuchanan
- [x] Upload Siemens b0 mapping test data #29 @fnery 
- [x] Upload T2* mapping test data #26 @charlotteebuchanan 
- [x] Document and tidy up `methods/T2Star` code #17 @alexdaniel654 
- [x] Write example/tutorial of T2* processing #16 @JSousa-UoL @fnery 
- [x] Write example/tutorial of B0 map processing #34 @JSousa-UoL @fnery
- [x] Decide on framework for unit tests #39 @fnery @alexdaniel654 
- [x] Implement unit tests @fnery @JSousa-UoL @alexdaniel654

---
Please add any comments/questions below.
